clc

% В данном файле производится расчет на предварительный выбор
% электродвигателя по мощности, а также занесение его характеристик

% Так как задача манипулятора - продолжительная работа с захватом посылок,
% где не нужна точность и поощряется продолжительность работы, почти на все
% оси можно спокойно ставить планетарные редукторы

eta = 0.9; % Примерное КПД
ksi = 1.25; % Коэффициент динамичности для следящих приводов высокой точности
i0 = [125, 125, 125, 100, 20];
% i0 = [125, 125, 125, 100, 20];

for ind = 1:5
    moments(ind).i = i0(ind);
    motor(ind).i = i0(ind);

    % приведенный к валу мотора статический момент
    M_stat_priv = ksi * (moments(ind).stat + moments(ind).react) / (moments(ind).i);

    % статический момент на редукторе
    M_stat_red = ksi * (moments(ind).stat  + moments(ind).react);

    % приведенный к валу мотора динамический момент
    M_din_priv = moments(ind).i * moments(ind).e * (moments(ind).J / (moments(ind).i ^2));

    % динамический момент на редукторе
    M_din_red = moments(ind).e * moments(ind).J;
    

    % пусковой момент
    M_start = M_stat_priv + M_din_priv;

    % пусковой момент на выходе редуктора
    M_start_red = M_stat_red + M_din_red;
    motor(ind).momred = M_start_red;
    

    % требуемые номинальные скорости мотора (rpm)
    rpm_nom_dvig = 60 * moments(ind).i * omega_max(ind) / (2 * pi);
    motor(ind).nnom = rpm_nom_dvig;
    motor(ind).nreq = motor(ind).nnom / motor(ind).i;

    % дополним расчет проверкой по мощности, чтобы проверить, что все
    % сработает (максимальная ммощность)

    P_max = ksi * omega_max(ind) * (moments(ind).stat + moments(ind).react) / eta;
    P_max2 = ksi * omega_max(ind) * (moments(ind).stat + moments(ind).react) + moments(ind).e * moments(ind).J / eta;
    %  + moments(ind).e * moments(ind).J
    if P_max == 0
        P_max = ksi * omega_max(ind) * moments(ind).e * moments(ind).J;
    end
    motor(ind).N = P_max;
    motor(ind).N_semi = P_max2;
    

    fprintf("Звено %.0f:\n" + ...
            "Статический момент: Mст = %.3f \n" + ...
            "Динамический момент: Mдин = %.3f\n" + ...
            "Пусковой момент: Mпуск = %.3f Н*м\n" + ...
            "Номинальная скорость: nном = %.3f rpm\n" + ...
            "Максимальная мощность: P_max = %.3f Вт\n" + ...
            "\n" + ...
            "Статический момент на редукторе: Mст_ред = %.3f \n" + ...
            "Динамический момент на редукторе: Mдин_ред = %.3f\n" + ...
            "Пусковой момент на редукторе: Mпуск_ред = %.3f Н*м\n" + ...
            "\n", ind, M_stat_priv, M_din_priv, M_start, rpm_nom_dvig, P_max, M_stat_red, M_din_red, M_start_red);
end

% После полученной информации, добавим моторам их параметры, найденные в
% интернете.

semimotor = struct('N', {}, 'nmot', {}, 'nreq', {});

index = 0;
for ind = 1:5
     fprintf("====================================\n" + ...
            "Параметры выбранного %.0f двигателя:\n" + ...
            "Требуемая скорость: nreqs = %.3f rpm\n" + ...
            "Номинальная скорость: nном = %.3f rpm\n" + ...
            "Номинальная мощность: P_max = %.3f Вт\n" + ...
            "Суммарный момент на выходе редуктора: Mmax = %.3f Нм\n" + ...
            "\n", ind, motor(ind).nreq, motor(ind).nnom, motor(ind).N, motor(ind).momred);
    index = index + 1;
    semimotor(index).N = motor(ind).N_semi; % Вт
    semimotor(index).nmot = motor(ind).nnom;
    semimotor(index).nreq = motor(ind).nnom / (motor(ind).i ^ (1/3));
    %fprintf("Параметры выбранного %.0f полумотора:\n" + ...
     %       "Требуемая скорость: nreqs = %.3f rpm\n" + ...
      %      "Номинальная скорость: nном = %.3f rpm\n" + ...
       %     "Номинальная мощность: P_max = %.3f Вт\n" + ...
        %    "\n", index, semimotor(index).nreq, semimotor(index).nmot, semimotor(index).N);
    for jnd = 2:3
        index = jnd + (ind - 1) * 3;
        semimotor(index).N = semimotor(index - 1).N; % Вт
        semimotor(index).nmot = semimotor(index - 1).nreq;
        semimotor(index).nreq = semimotor(index - 1).nreq / (motor(ind).i ^ (1/3));        
        %fprintf("Параметры выбранного %.0f полумотора:\n" + ...
         %       "Требуемая скорость: nreqs = %.3f rpm\n" + ...
          %      "Номинальная скорость: nном = %.3f rpm\n" + ...
           %     "Номинальная мощность: P_max = %.3f Вт\n" + ...
            %    "\n", index, semimotor(index).nreq, semimotor(index).nmot, semimotor(index).N);
    end    
end

reducer = struct('u', {}, 'k', {}, 'C', {}, 'gamma', {}, ...
                 'nah', {}, 'nbh', {}, 'nch', {}, ...
                 'etarel', {}, 'eta', {}, 'etamuf', {}, ...
                 'Ndvig', {}, 'N1', {}, 'N2', {}, 'T1', {}, 'T2', {}, ...
                 'HBg', {}, 'HBw', {}, 'NHO1', {}, 'NHO2', {}, 'NFO1', {}, 'NFO2', {},...
                 't', {}, 't1', {}, 't2', {}, 't3', {}, 'tHE', {}, 'NHE1', {}, 'NHE2', {}, 'mode', {}, ...
                 'sigmaHO1', {}, 'sigmaHO2', {}, 'sigmaFO1', {}, 'sigmaFO2', {}, ...
                 'KHL1', {}, 'KHL2', {}, 'KFL1', {}, 'KFL2', {}, ...
                 'sigmaH1', {}, 'sigmaH', {}, 'sigmaH2', {}, 'sigmaF1', {}, 'sigmaF2', {}, ...
                 'SH1', {}, 'SH2', {}, 'SF1', {}, 'SF2', {}, ...
                 'Kd', {}, 'psibd', {}, 'uHaC', {}, 'Tap', {}, 'Kc', {}, 'Khbetta', {}, 'Ta', {}, ...
                 'm', {}, 'za', {}, 'zb', {}, 'zc', {}, 'da', {}, 'db', {}, 'dc', {}, 'ba', {}, 'bb', {}, 'bc', {}, 'V', {}, 'na', {}, ...
                 'Zm', {}, 'Zh', {}, 'Ze', {}, 'epsilona', {}, 'grade', {}, 'Kha', {}, 'Khc', {}, 'Khv', {}, 'sigmah', {}, ...
                 'Kfv', {}, 'Kfa', {}, 'Kfbetta', {}, 'YF1', {}, 'YF2', {}, 'Ke', {}, 'mt', {}, 'sigmaFC', {}, ...
                 'Vc', {}, 'sigmah_e', {}, 'Ze_e', {}, 'epsilona_e', {});

%semimotor(9).nmot = 975;
%semimotor(9).nreq = 210;
%semimotor(9).N = 11000;

